---
driver:
  name: ec2
  aws_ssh_key_id: chef-aws-adfs
  region: ap-southeast-2
  require_chef_omnibus: true
  associate_public_ip: true
  instance_type: t2.nano

provisioner:
  name: chef_solo

transport:
  ssh_key: ~/.ssh/chef-aws-adfs.pem

platforms:
  - name: Amazon-Ubuntu-14.04
    driver:
      image_id: ami-ba3e14d9
  # - name: Amazon-Linux-2016.09.0
  #   driver:
  #     image_id: ami-55d4e436
  - name: RedHat-7.2
    driver:
      image_id: ami-e0c19f83
      instance_type: t2.micro

suites:
  - name: default
    run_list:
      - recipe[aws-adfs::default]
    attributes:
